language: cpp
dist: xenial
stages:
  - test
  - upgrade_minor
  - upgrade_major

jobs:
  include:
    stage: test

    before_script:  
      - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
      - tar xzf release-1.8.0.tar.gz
      - cd googletest-release-1.8.0
      - mkdir build && cd build
      - cmake ..
      - make -j
      - sudo cp -r ../googletest/include /usr/local/include
      - sudo cp -r ./googlemock/gtest/libgtest*.a /usr/local/lib/
      - sudo cp -r ./googlemock/libgmock*.a /usr/local/lib/
      - cd ../../
      - make compile_test

    script:
      - ./a.out
